"""init

Revision ID: 8fe970593fa3
Revises: 
Create Date: 2025-04-17 11:33:33.726353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe970593fa3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text("timezone('utc', now())"), autoincrement=True, nullable=True),
    sa.Column('update_at', sa.TIMESTAMP(), server_default=sa.text("timezone('utc', now())"), autoincrement=True, nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text("timezone('utc', now())"), autoincrement=True, nullable=True),
    sa.Column('update_at', sa.TIMESTAMP(), server_default=sa.text("timezone('utc', now())"), autoincrement=True, nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), nullable=False),
    sa.Column('preferences', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_org', sa.Boolean(), nullable=True),
    sa.Column('date_of_birth', sa.String(), nullable=True),
    sa.Column('like_events', sa.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text("timezone('utc', now())"), autoincrement=True, nullable=True),
    sa.Column('update_at', sa.TIMESTAMP(), server_default=sa.text("timezone('utc', now())"), autoincrement=True, nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('external_url', sa.VARCHAR(), nullable=True),
    sa.Column('date_event', sa.DATE(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('duration', sa.TIME(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.Column('age_limit', sa.VARCHAR(), nullable=True),
    sa.Column('picture_url', sa.VARCHAR(), nullable=True),
    sa.Column('horizontal_picture_url', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('info_org',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_to_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), autoincrement=True, nullable=False),
    sa.Column('update_at', sa.TIMESTAMP(), autoincrement=True, nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('date_event', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_to_event')
    op.drop_table('info_org')
    op.drop_table('event')
    op.drop_table('user')
    op.drop_table('group_event')
    # ### end Alembic commands ###
