"""Create table for parse

Revision ID: 8d8a6ca01dd4
Revises: ad1619a2f614
Create Date: 2026-04-28 15:23:34.132511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d8a6ca01dd4'
down_revision: Union[str, None] = 'ad1619a2f614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsed_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text("timezone('utc', now())"), autoincrement=True, nullable=True),
    sa.Column('update_at', sa.TIMESTAMP(), server_default=sa.text("timezone('utc', now())"), autoincrement=True, nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('source_key', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('date_event', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('age_limit', sa.String(), nullable=True),
    sa.Column('external_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'date_event', name='parsed_event_name_date_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parsed_event')
    # ### end Alembic commands ###
